language: ruby
rvm:
- 2.3
sudo: required
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y nginx imagemagick
script: ./script/cibuild
branches:
  only:
  - master
  - /feature/(.+)/
  - /posts/(.+)/
  - /post/(.+)/
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
deploy:
  provider: s3
  access_key_id: AKIAJLRSYSS26S7OJIJA
  secret_access_key:
    secure: X13ts3pxBFbyoI9+A4KqIE6E/MGkv70KElgIwYeatreVXwgDn7JJSjWXz8S6E5BvTc+Oir7F4Q0WsonqpFIn1KKa3Z11XqdQ22b4iEgXKt5BPnuHBAxh5MnAudOfrp0oRSR9SK3yLVt2QuKJX/bAJUdq7q2lwzUg9VoJLfqwggtpAdlKdLXilA3D015j0IJocATIo7Ka8GMe/wl+A9rQmVElQS7VmSnxzb5lOKGItEG38N/6BMxB5L5LJ1ugXmbipGKDfGqV6xFcorq/PcgKws51Q4l11mR6lXZ8FprheIEenAdQb5JRyrJ71WSwPFaZmLozWj1i38bGpKiKBHGTQfEPUO2QBZHC424TzGkpsDMoExF2Bv6an+3vjoAWJUEru5+/H/8ABEJdeo0m6tCoJqPDVrKtSyGoe/QATB6yZz2PpKRdXdU5EcM+o8dH0pN62Kh37ySSn2LKv99AMLaaMhMr7PJHDnA4FDko/8LuH80m0Vx1FxooZmoD3JW2LzucFHUCACLfScMsC9ahaVYagxRErKWPGDZfq1aMGYfjzl313pDUt7xXd54v2H8mlisG0CrnncNO+DGVwrbZKSicswoAejCmH8mtQN3hXBf71OItQglkrm+inKGQSdmfD5pGxohf/5cleTiOeMwxYGlahWfbS5Mq/bdbI7U6RBij9jA=
  bucket: net-jamesoff-www
  local-dir: _build
  acl: private
  on:
    repo: jamesoff/www-jamesoff-net
    branch: master
  skip_cleanup: true
  region: eu-west-1
notifications:
  slack:
    secure: MpqAVbPi8K0o09NFgUPLS3ZiF33Ilzn8lz095MZbsD5W8pAWTVb+xOlBEpSmDuNeqdIg63gN2jKSBPFwoR9YMOiNeuzozFOz5YYlzZn+wZsSDAs+a8b9FrV6LzEbCJSkGnMWUHpTobC7q4sD4RIS++RdyDm/imjO/rbe5oROipS3vW0OzuA/oALL6ScKRSEWeaqKyX6DafSAmlypoqC/5RSXErmIPeD/igKtoRukSokBfVtzsoFdq226vpQ2xTh75qQ1Ogi8aJsHadAwZ1KgIEGShzdktJdB7l5mo+VHlOhzH7bxv6BJvUjrFSR5lVmg8wSjC4sV9XrHswXtDPJ4ylaLNGYdpmGJxrmE84kupAEyvnt6fhlhD6XjMTsNBvoDY2l1GJyqJLRRZVRj3fkFr5sVWzJhtisOx/wbOI+U9TN7JgAMBEaGJp83BpmI8OfY6T7PWEr53mG7Boh25Qca7Xz5Csz0+VpMQv6jfGdmx4F8zKSNI6mjY2CX/CHS6uMEMXXyzqKtUCY8MKOwqysBw6D4W3tnTtCJyiPoTSahisA0Cu49fx0R3VfpyPLfg3uw9KUjXQQmt45Lz+NhWfKNe61JH3ktMwIVkvP3zAa45tT3CFfr1TDpc4TUAzFJM9eLLm09fK1/5qjJ7h+G7BQWWGEMSykvAcyDa3TMImIJxQY=
  webhooks:
    urls: https://jamesoff.net/_webhook/
    on_success: always
    on_failure: never
    on_start: never

