# Site settings
title:       jamesoff.net
email:       james@jamesoff.net
author:      James Seward
description: "a random code generator"
baseurl:     ""
url:         "https://jamesoff.net"
strapline:   a random code generator

# Google analytics
# google_analytics: UA-325830-2

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false
show_social_icons:  false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username: jamesoff
bitbucket_username:
stackoverflow_id:
twitter_username: jamesoff
google_plus_id:
linkedin_username:
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
share_text: 'Share this post!'
# Change to 'true' to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    /:year/:month/:day/:title.html
paginate:     4
sass:
  compressed: true
  style: compresed
gems:
  - jekyll-paginate
  - jekyll-gist
exclude:
    - vendor
    - script
    - Gemfile
    - Gemfile.lock
include:
    - _htaccess
    - well-known
sitemap:
    exclude:
        - /googleff360c83a8c3e0c4.html
        - /404.md
        - /archive
        - f/index.html
        - /feed.xml
        - /_htaccess
        - /css/pixyll.scss
        - /nginx-rewrites
        - /BingSiteAuth.xml
    include_posts:
        - /index.html
highlighter: rouge
image:
  source: i
  output: generated
  presets:
    half:
      width: 420
      filter: Box
    big:
      width: 840
      filter: Box
plugins:
  - jekyll-paginate
keep_files:
  - .well-known/webfinger
