source "https://rubygems.org"

gem "pkg-config"
gem "activesupport", "~> 6.1"
gem "jekyll"
gem "jekyll-paginate"
gem "html-proofer"
gem "rouge"
gem "jekyll-gist"
gem "mini_magick"
gem "nokogiri", "~> 1.11.2"
